//
//  Constants.swift
//  uncover
//
//  Created by Bekzod Rakhmatov on 10/06/23.
//

import Foundation

let invalidURLError = "URL is invalid."
let baseURL = "https://api-stage.theuncoverapp.com/api"
let initialData = "/v1/initial-data/"
let bookForm = "/v1/book-form/"
let bookList = "/v1/books-list/%@/"
let booksByTag = "/v1/books/by-tag/%@/"
let booksById = "/v1/books/%@/"
let bookIdCover = "/v1/books/%@/cover/"
let featuredInPreview = "/v1/books/%@/featured-in-preview/"
let featuredIn = "/v1/books/%@/featured-in/"
let bookLikes = "/v1/books/%@/likes/"
let bookReaction = "/v1/books/%@/reaction/"
let bookReaderPreview = "/v1/books/%@/readers-preview/"
let bookReaders = "/v1/books/%@/readers/"
let reportBookEndpoint = "/v1/books/%@/report/"
let similarBooksPreview = "/v1/books/%@/similar-books-preview/"
let similarBooksEndpoint = "/v1/books/%@/similar-books/"
let bookStatusEndpoint = "/v1/books/%@/status/%@/"
let bookTagEndpoint = "/v1/books/%@/tag/"
let bookTagPreviewEndpoint = "/v1/books/%@/tags-preview/"
let deckFollowersEndpoint = "/v1/deck-followers/"
let getDecksEndpoint = "/v1/decks/"
let getDeckIdEndpoint = "/v1/decks/%@/"
let blockDeckEndpoint = "/v1/decks/%@/block/"
let deckBooksEndpoint = "/v1/decks/%@/books/"
let deckIdFollowersEndpoint = "/v1/decks/%@/followers/"
let deckLikesEndpoint = "/v1/decks/%@/likes/"
let deckReactionEndpoint = "/v1/decks/%@/reaction/"
let readBooksCountEndpoint = "/v1/decks/%@/read-books-count/"
let deckTagEndpoint = "/v1/decks/%@/tag/"
let followersEndpoint = "/v1/followers/"
let homeModulesEndpoint = "/v1/home-modules/"
let homeModuleByIdEndpoint = "/v1/home-modules/%@/"
let homeModuleBooksEndpoint = "/v1/home-modules/%@/books/"
let homeModuleDecksEndpoint = "/v1/home-modules/%@/decks/"
let notificationRegisterEndpoint = "/v1/notification-register/"
let notificationUnregisterEndpoint = "/v1/notification-unregister/"
let notificationsMarkkReadEndpoint = "/v1/notifications-mark-read/"
let userNotificationsEndpoint = "/v1/notifications/%@/"
let profilePictureEndpoint = "/v1/profile_pictures/"
let userProfilePictureEndpoint = "/v1/profile_pictures/%@/"
let reactionEndpoint = "/v1/reactions/%@/"
let reactionLikesEndpoint = "/v1/reactions/%@/likes/"
let reactionRepliesEndpoint = "/v1/reactions/%@/replies/"
let reactionReportEndpoint = "/v1/reactions/%@/report/"
let tagsEndpoint = "/v1/tags/"
let tagsIdEndpoint = "/v1/tags/%@/"
let trendingBooksEndpoint = "/v1/trending/books/"
let trendingDecksEndpoint = "/v1/trending/decks/"
let trendingTagsEndpoint = "/v1/trending/tags/"
let trendingUsersEndpoint = "/v1/trending/users/"
let usersEndpoint = "/v1/users/"
let emailAvailabilityEndpoint = "/v1/users/email_availability/"
let usernameAvailabilityEndpoint = "/v1/users/username_availability/"
let welcomeEmailEndpoint = "/v1/users/welcome_email/"
let firebaseUidEndpoint = "/v1/users/%@/"
